language: cpp
dist: bionic
cache: ccache
cache:
  directories:
    - /home/travis/_install
os:
  - linux

env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install

addons:
  apt:
    sources: &clang7_sources
      - llvm-toolchain-bionic-7
    sources: &clang8_sources
      - llvm-toolchain-bionic-8
    packages: &base_packages
      - libboost-all-dev
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - cmake
      - cmake-data

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-5
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - g++-5
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-6
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - g++-6
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-7
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - g++-7
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-8
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-8
    - compiler: gcc
      env: GCC_VERSION=9 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *base_packages
            - g++-9
            - gfortran-9
    - compiler: gcc
      env: GCC_VERSION=9 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *base_packages
            - g++-9
            - gfortran-9
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - g++-8
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - g++-8
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt: 
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - g++-8
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - g++-8
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
    - compiler: clang
      env: CLANG_VERSION=9 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
    - compiler: clang
      env: CLANG_VERSION=9 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev

before_install:
  - env
  - mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat build/CMakeFiles/CMakeOutput.log
  - cat build/CMakeFiles/CMakeError.log
  - cat build_cblas/CMakeFiles/CMakeOutput.log
  - cat build_cblas/CMakeFiles/CMakeError.log
notifications:
  email:
    recipients:
      - eduard+btas@valeyev.net
    on_success: change
    on_failure: always
