language: cpp
os:
  - linux

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
      - boost-latest
      - kubuntu-backports
    sources: &clang_sources
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0
      - llvm-toolchain-trusty-7
      - llvm-toolchain-trusty
    packages: &base_packages
      - libboost1.55
      - libboost1.55-dev
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libopenblas-dev
      - cmake
      - cmake-data

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-5
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-5
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-6
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-6
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-7
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-7
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang_sources
          packages:
            - *base_packages
            - g++-8
            - clang-7
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang_sources
          packages:
            - *base_packages
            - g++-8
            - clang-7
before_install:
  - ./bin/travisci_before_$TRAVIS_OS_NAME.sh
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat build/CMakeFiles/CMakeOutput.log
  - cat build/CMakeFiles/CMakeError.log
  - cat build_cblas/CMakeFiles/CMakeOutput.log
  - cat build_cblas/CMakeFiles/CMakeError.log
notifications:
  email:
    recipients:
      - eduard+btas@valeyev.net
    on_success: change
    on_failure: always
