language: cpp
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:boost-latest/ppa -y && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update && sudo apt-get install -y g++-4.8 llvm-3.4 llvm-3.4-dev libboost1.55-dev libboost-serialization1.55-dev cmake; fi
notifications:
  email:
    recipients:
      - eduard+btas@valeyev.net
    on_success: change
    on_failure: always
os:
  - linux
after_failure:
  - cat CMakeFiles/CMakeOutput.log
  - cat CMakeFiles/CMakeError.log
script:
  - mkdir build && cd build &&  if [ $CXX == gcc ]; then export CXX=/usr/bin/g++-4.8; fi && cmake .. && make VERBOSE=1 && make check VERBOSE=1
